---
title: "tidy_r_weenkd_hw"
output: html_document
---
```{r}
library(tidyverse)
```


```{r}
library(janitor)
```

```{r}
library(tidyr)
```

```{r}
women_in_gov <- read.csv("women_in_gov.csv", skip = 3)
```
/* Some of the column names contain spaces and numbers. Fix the column names. */


```{r}
women_in_gov_clean <- women_in_gov %>%
clean_names()
names(women_in_gov_clean)

```

/*q3.     */

```{r}
women_in_gov_clean %>% distinct(x1964)
women_in_gov_clean %>% distinct(indicator_name)
```
/* remove redundant col  */
```{r}
women_in_gov2 <- women_in_gov_clean %>% 
  select(-indicator_name, -indicator_code, -x1964)
```





```{r}
women_in_gov_long <- women_in_gov2 %>%
  pivot_longer(cols = starts_with("x"), 
               names_to = "year", 
               values_to = "prop_women")

women_in_gov_long
    
```
/* 8.*/

```{r}
women_in_gov_long %>%
  summarise(count = sum(is.na(prop_women)))
  

```
```{r}
missing_gov <- women_in_gov_long %>% 
  select(prop_women) %>% 
  filter(is.na(prop_women))
unique(missing_gov$prop_women)
```
```{r}
women_in_gov <- women_in_gov_long %>%
  drop_na()
```

/*9.    */


```{r}
ggplot(women_in_gov, aes(x = "prop", y = prop_women)) +
    geom_boxplot()

```
/*10 -    */
```{r}
library(outliers)

# get the z-scores for each value in prop_women
prop_zscores <- scores(women_in_gov$prop_women)

# add a column with info whether the refund_value is an outlier
is_outlier <- prop_zscores > 3 | prop_zscores < -3
women_in_gov <- women_in_gov %>%
  mutate(is_outlier = is_outlier)

# create a table with only outliers
women_outliers <- women_in_gov %>% 
  filter(is_outlier == TRUE)

women_no_outliers <- women_in_gov %>%
  filter(is_outlier == FALSE)
```

```{r}

```

/*12-    */
```{r}
top_10_women <- women_no_outliers %>%
                  arrange(country_name, country_code, year) %>%
                  group_by(country_name, country_code) %>%
                  summarise(mean_women = mean(prop_women)) %>%
                  arrange(desc(mean_women)) %>%
                  head(10)

top_10_women
```
```{r}
bottom_10_women <- women_no_outliers %>%
                  arrange(country_name, country_code, year) %>%
                  group_by(country_name, country_code) %>%
                  summarise(mean_women = mean(prop_women)) %>%
                  arrange(mean_women) %>%
                  head(10)

bottom_10_women
```


