---
title: "w6d2_hw"
author: "nehali"
date: "15/04/2020"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)

```

```{r}
phones <- read_csv("data/20190928-items.csv")
phones <- clean_names(phones)
glimpse(phones)
```
#* Find the brand with the highest numbers of phones in the dataset.
```{r}
top_brand <- phones %>%
  group_by(brand) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  top_n(1)
top_brand
  
```
#2For your top brand, plot the distribution of phone ratings as a probability density, overlaying a fitted normal distribution. Do you think the normal distribution provides a good model of these ratings?
```{r}
samsung_ratings <- phones %>%
  filter(brand == "Samsung") %>%
  select(rating)
samsung_stats <- phones %>%
  filter(brand == "Samsung") %>%
  summarise(
    count = n(),
    mean = mean(rating),
    sd = sd(rating)
  )
samsung_stats
samsung_stats_fitdistr <- MASS::fitdistr(x = samsung_ratings$rating, densfun = "normal")
samsung_stats_fitdistr

```
#4
```{r}
samsung_ratings %>%
  ggplot(aes(x = rating)) +
  geom_histogram(aes(y = ..density..), col = "white") +
  stat_function(
    fun = dnorm, 
    args = list(
      mean = samsung_stats$mean,
      sd = samsung_stats$sd
    ),
    col = "red"
  )
```
```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + samsung_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_ratings))
```
#FOR 2 SD
```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - 2 * samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + 2 * samsung_stats$sd) %>%
  summarise(prop_within_2sd = n() / nrow(samsung_ratings))
```
#FOR 3SD
```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - 3 * samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + 3 * samsung_stats$sd) %>%
  summarise(prop_within_3sd = n() / nrow(samsung_ratings))
```

#EXTENSION

```{r}
library(car)
```




```{r}
qqPlot(samsung_ratings$rating)

```


```{r}

```

