---
title: "w5_d2 hw"
author: "nehali"
date: "08/04/2020"
output: html_document
---

```{r}
library(tidyverse)
library(CodeClanData)
library(ggplot2)
```

```{r}
qb_rev <- qb_revenue_breakdown
qb_rev
```

```{r}
ggplot(qb_rev) +
  (aes(x = Year, fill = Product, y = Revenue)) +
     geom_col()
             

```
#2
```{r}
kwikbit_sales <- subset(qb_monthly_sales, Cashflow == "Kwikbit Unit 1 Sales")
ggplot(kwikbit_sales) +
  aes(x = Date, y = Amount) +
  scale_x_discrete(breaks = c("lots of writing")) +
  geom_line()
```
```{r}
qb_monthly_sales
```


#3

```{r}
 revenue_and_costs <- subset(qb_monthly_sales, Cashflow != "Kwikbit Unit 1 Sales")
ggplot(revenue_and_costs) +
  aes(x = Date, y = Amount, colour = Cashflow) +
  geom_line()
```
```{r}
qb_competitors
```


#4
```{r}
ggplot(qb_competitors) +
  aes(x = Year, y = Revenue,fill = Company ) +
  geom_area()
```
#5
```{r}
ggplot(qb_competitors) +
  aes(x = Year, y= Revenue, colour = Company) +
  geom_line() +
geom_point()
```
```{r}
qb_device_data
```

#6
```{r}

qb_device_data <- mutate(qb_device_data, hours_1 = (hours) + mins/60)
ggplot(qb_device_data) +
  aes(x = hours_1, y = counts) +
  geom_line() +
  facet_grid(id ~ device)
```

