---
title: "dplyr_practice"
output: html_document
---
```{r}
library(dplyr)
library(janitor)
library(readr)
```

```{r}
salaries <- read.csv("data/salaries.csv")
salaries
```

```{r}
select(salaries,'beginning_salary', 'current_salary')

```

```{r}
salary_50 <- salaries %>%
  
  filter(age > 50) %>%
filter(current_salary > 20000) 
salary_50


```

```{r}
salaries %>%
  select(current_salary) %>%
  arrange(desc(current_salary))
```

```{r}
salaries %>%
  mutate(beginning_salary_pence = beginning_salary * 100, current_salary_pence = current_salary *100)
```


```{r}
min_max_age <- salaries %>%
  select(age) %>%
  filter(!is.na(age)) %>%
  summarise(max(age), min(age)) 
  min_max_age
```

```{r}
min_max_salary <- salaries %>%
  select(current_salary) %>%
  summarise(min(current_salary), max(current_salary))
min_max_salary
```

```{r}
emp_under_30 <- salaries %>%

  filter(age < 30)
emp_under_30
  
  
```

```{r}
salaries %>%
  select(beginning_salary,job_seniority,age, educational_level,gender, current_salary,work_experience, employment_category, is_white) 
  arrange(salaries,desc(educational_level))
 
  
```

```{r}
salaries %>%
  filter(is.numeric(salaries) == FALSE) %>%
  drop()
  
  
  
```

```{r}
emp_exp_less_then2_edu_less_then_12 <- salaries %>%
  select(work_experience,educational_level,age, job_seniority,beginning_salary,gender,age,employment_category) %>%
filter((work_experience < 2) | (educational_level < 12))
  
 emp_exp_less_then2_edu_less_then_12 
```

```{r}
salary_in_1000s <- salaries %>% 
  select(beginning_salary, current_salary) %>%
  rename(beginning_salary_in_1000s = beginning_salary,  current_salary_in_1000s = current_salary) %>%
  transform(beginning_salary_in_1000s = beginning_salary_in_1000s/1000, current_salary_in_1000s = current_salary_in_1000s/1000)
  salary_in_1000s
```



```{r}
female_emp <- salaries %>%
  select('employment_category','gender') %>%
filter(employment_category == 'security officer', gender == 'female')
female_emp
```



```{r}
avg <- salaries %>%
  select(current_salary, employment_category) %>%
group_by(employment_category) %>% 
summarise(mean(current_salary))

```


```{r}
avg_males <- salaries %>%
  select(current_salary, employment_category,gender) %>%
  filter(gender == "male") %>%
group_by(employment_category) %>% 
summarise(mean(current_salary))
```




```{r}
salaries %>%
  group_by(gender, is_white) %>%
  summarise(n()) 
 
```




```{r}
salaries %>%
  mutate(mean_age = mean(current_salary)) %>%
  View()
```

#PIPES


```{r}
salaries %>%
  select(current_salary,educational_level) %>%
filter(educational_level <= 16) %>%
  group_by(educational_level) %>%
  summarise(mean(current_salary))
 
 

```



.


```{r}
salaries %>%
  select(employment_category, current_salary,gender,work_experience) %>%
filter(work_experience < 2)%>%
  group_by(gender = 'male',employment_category) %>%
 summarise(mean(current_salary)) 

salaries %>%
  select(employment_category, current_salary,gender,work_experience) %>%
filter(work_experience < 2)%>%
group_by(gender = 'female', employment_category) %>%
  summarise(mean(current_salary))
  
```
#3

```{r}
salaries %>%
  select(employment_category,current_salary) %>%
  group_by(employment_category) %>%
  summarise(mean('college trainee'), mean('exempt employee'), mean('clerical'))
  
```

#3missing values


#1
```{r}
beer <- read.delim("data/beer.txt", sep = "|", dec = ",")
beer
```

```{r}
beer <- clean_names(beer)
```

```{r}
beer %>%
  filter(beer,na.rm == TRUE)
  
 
  
```

