---
title: "Decathalon_project"
output: html_document
---

```{r}
library(janitor)
library(tidyverse)
library(tidyr)
library(stringr)
library(rebus)
library(dplyr)
library(CRANsearcher)
```


```{r}
decathlon <- readRDS("decathlon.rds")
decathlon
```

```{r}
decathlon_clean <- clean_names(decathlon)
decathlon_clean
```

```{r}
decathlon_clean %>%
  rownames_to_column("Name")
```
```{r}
names(decathlon_clean) <- c("X100m", "Long_jump", "Shotput", "High_jump", "X400m","X110m_Hurdle", "Discus","Pole_vault", "Javelin" , "X1500m", "Rank", "Points", "Competition") 
decathlon_clean <- decathlon_clean %>% rownames_to_column("Name") %>% mutate(Competition = as.character(Competition))
```

```{r}
## parsed with column specification
## cols(
## 'Name' = col_character(),
## 'X100m' = col_double(),
## 'Long_jump' = col_double(),
## 'Shot_put' = col_double(),
## 'High_jump' = col_double(),
## 'X400m' = col_double(),
## 'X110m_hurdle' = col_double(),
## 'Discus' = col_double(),
## 'Pole_vault' = col_double(),
## 'Javeline' = col_double(),
## 'X1500m' = col_double(),
## 'Rank' = col_double(),
## 'Points' = col_double(),
## 'Competition' = col_character()

## )
```

```{r}
decathlon_clean 
```

```{r}
decathlon_clean %>%
  head('Long_jump') %>%
head(1)
```




```{r}
decathlon_clean %>%
  select(X100m,Competition) %>%
  filter(Competition == 'Decastar') %>%
  group_by(Competition) %>%
  filter(!is.na(X100m)) %>%
 summarise(mean = mean(X100m)) 
decathlon_clean %>%
select(X100m, Competition) %>%
  filter(Competition == 'OlympicG') %>%
    group_by(Competition) %>%
    filter(!is.na(X100m)) %>%
    summarise(mean = mean(X100m))
```

```{r}
decathlon_clean %>%
  distinct(Name,Points,Competition) %>%
  group_by(Name) %>%
  summarise(total = sum(Points)) %>%
  arrange(desc(total)) %>%
  head(1)
  

```

```{r}
decathlon_clean %>%
  select(Shotput,Rank) %>%
  filter(rank<= 3) %>%
  head(3)
    
```



```{r}
decathlon_clean %>%
  select(X400m,Points) 
  group_by(fast_400)
  summarise(avg = mean(Points))

```







