---
title: "CI-minilab"
author: "nehali"
date: "16/04/2020"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```

```{r}
ames <- read.csv("ames.csv")
ames
```
```{r}
ames <- clean_names(ames)
ames
```
```{r}
glimpse(ames)
```

```{r}
hist <- ames %>%
  ggplot(aes(x = sale_price)) +
  geom_histogram(col = "white")
hist
```
It is significanyly right skewed

#calculating population parameter
```{r}
param <- mean(ames$sale_price)
param
```

#1000 samples, each of size 100 
```{r}
results <- tibble()
for(sample_num in 1:1000) {
  this_sample <- ames %>%
    rep_sample_n(size =100, reps = 1) %>%
    ungroup() %>%
    select(sale_price)
  
  bootstrap_1000 <- this_sample %>%
    specify(response = sale_price) %>%
    generate(reps = 1000, type = "bootstrap") %>%
    calculate (stat = "mean")
  
  this_ci <- bootstrap_1000 %>%
    get_ci(level = 0.95, type = "percentile")
  
  this_result <- c(
    sample_num = sample_num,
    lower = this_ci [[1]],
    upper = this_ci [[2]]
  )
  results <- bind_rows(results, this_result)
}
```


```{r}
results <- results %>%
mutate(popn_param_in_ci = lower <= param$mean_sale_price & param$mean_sale_price <= upper)
```



